import "./globals.css";
import { Inter, IBM_Plex_Sans } from "next/font/google";
import NavBar from "Components/NavBar";
import ThemeRegistry from "styles/theme/ThemeRegistry";

const inter = Inter({ subsets: ["latin"] });
const ibm_plex_sans = IBM_Plex_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </head>
      <body className={ibm_plex_sans.className}>
        <ThemeRegistry options={{ key: "css" }}>
          <NavBar>{children}</NavBar>
        </ThemeRegistry>
      </body>
    </html>
  );
}
