import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "Components/NavBar";
import ThemeRegistry from "@/styles/theme/ThemeRegistry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeRegistry options={{ key: "css" }}>
          <NavBar />
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
